<?xml version="1.0"?>

<robot name="limo_four_diff_robot" xmlns:xacro="http://ros.org/wiki/xacro">
    <!-- a lightweight robot geometry model -->
    <xacro:arg name="model_lite" default="true" />

    <xacro:include filename="$(find for_open_scout)/urdf/limo_robot.xacro" />

    <!-- Variables -->
    <xacro:property name="M_PI" value="3.14159"/>

    <!-- Vehicle Geometries -->
    <xacro:property name="base_x_size" value="0.13" />
    <xacro:property name="base_y_size" value="0.12" />
    <xacro:property name="base_z_size" value="0.1" />

    <xacro:property name="wheelbase" value="0.2"/>
    <xacro:property name="track" value="0.13"/>
    <xacro:property name="wheel_vertical_offset" value="-0.10" />
    <xacro:property name="base_mass" value="2.1557"/>

    <xacro:property name="wheel_length" value="0.045" />
    <xacro:property name="wheel_radius" value="0.045" />

    <!-- Base link -->
    <link name="base_link">
        <visual>
            <origin xyz="0 0 -0.15" rpy="0 0 1.57" />
            <geometry>
                <xacro:if value="$(arg model_lite)">
                    <mesh filename="file://$(find for_open_scout)/models/limo_base_lite.dae" scale="1 1 1"/>
                </xacro:if>
                <xacro:unless value="$(arg model_lite)"> 
                    <mesh filename="file://$(find for_open_scout)/models/limo_base.dae" scale="1 1 1"/>
                </xacro:unless>
            </geometry>
        </visual>
        <collision>
            <!--origin xyz="0 0 -0.15" rpy="0 0 1.57" /-->
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
            </geometry>
        </collision>
    </link>

    <link name="base_footprint"/>

    <joint name="base_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0.0 0.0 -0.15" rpy="0 0 0"/>
    </joint>

    <link name="inertial_link">
        <inertial>
            <origin xyz="0.0 0.0 0.0" />
            <mass value="${base_mass}" />
            <inertia ixx="0.24" ixy="0" ixz="0" iyy="0.96" iyz="0" izz="0.96" />
        </inertial>
    </link>

    <joint name="inertial_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="inertial_link" />
    </joint>

    <xacro:limo_wheel parent_prefix="base_link" wheel_prefix="front_left" reflect="1" model_lite="$(arg model_lite)">
        <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0  0" />
    </xacro:limo_wheel>

    <xacro:limo_wheel parent_prefix="base_link" wheel_prefix="front_right" reflect="-1" model_lite="$(arg model_lite)">
        <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="${M_PI} 0 0" />
    </xacro:limo_wheel>

    <xacro:limo_wheel parent_prefix="base_link" wheel_prefix="rear_left" reflect="1" model_lite="$(arg model_lite)">
        <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:limo_wheel>

    <xacro:limo_wheel parent_prefix="base_link" wheel_prefix="rear_right" reflect="-1" model_lite="$(arg model_lite)">
        <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="${M_PI} 0 0" />
    </xacro:limo_wheel>

</robot>
