<?xml version="1.0"?>
<robot name="limo_robot" xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:macro name="limo_wheel" params="parent_prefix wheel_prefix reflect model_lite *joint_pose">
        <link name="${wheel_prefix}_wheel_link">
            <inertial>
                <origin xyz="0 0 0" />
                <mass value="0.5" />
                <inertia ixx="0.01055" ixy="0" ixz="0" iyy="0.00075" iyz="0" izz="0.01055" />
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <xacro:if value="${model_lite}">
                        <mesh filename="file://$(find limo_description)/meshes/limo_wheel_lite.dae"/>
                    </xacro:if>
                    <xacro:unless value="${model_lite}"> 
                        <mesh filename="file://$(find limo_description)/meshes/limo_wheel.dae"/>
                    </xacro:unless>                
                </geometry>
            </visual>
            <collision>
              <origin xyz="0 ${wheel_length/2} 0" rpy="1.57 0 0" />
              <geometry>
                  <cylinder length="${wheel_length}" radius="${wheel_radius}" />
              </geometry>
            </collision>
        </link>

        <joint name="${wheel_prefix}_wheel" type="continuous">
            <parent link="${parent_prefix}"/>
            <child link="${wheel_prefix}_wheel_link"/>
            <xacro:insert_block name="joint_pose"/>
            <axis xyz="0 ${reflect*1} 0"/>
        </joint>
    </xacro:macro>

</robot>
